name: Sarath Kossery Prakasan
tagline: Postdoctoral researcher
career-objective: A dedicated and results-oriented aerospace engineer specializing in Direct Numerical Simulations (DNS) and Reduced Order Modeling (ROM) to investigate the physical mechanisms driving transition to turbulence in fluid flows. Experienced in leveraging High-Performance Computing (HPC) systems to perform large-scale simulations and generate accurate aerodynamic insights. Possesses strong analytical and problem-solving skills, consistently delivering innovative, high-quality solutions to complex engineering challenges. Recognized for effective leadership, adaptability, and communication, contributing successfully to multidisciplinary research and engineering teams.
color-theme: red # red or blue
avatar-filename: SarathKP.jpg # Change to your avatar's filename
url: sarath-prakash.github.io/Resume_Sarath/
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: sarath.kossery@gmail.com
  github: 
    visibility: true
    handle: sarath-prakash
  linkedin: 
    visibility: true
    handle: sarath-k-prakash
  twitter: 
    visibility: false
    handle: 

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: year

# About Page Options
collection_option:
  experience: 
    label: Experience
    visibility: true
  education: 
    label: Education
    visibility: true
  projects: 
    label: Projects
    visibility: true
  skills: 
    label: Technical Skills
    visibility: true
  publications: 
    label: Publications
    visibility: true
  volunteerexperience: 
    label: Volunteer Experience
    visibility: true
  certifications: 
    label: Certifications
    visibility: true
  achievements: 
    label: Achievements
    visibility: true

navigation:
- title: About
  url: /
- title: Blog
  url: /blog/
- title: Contact
  url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UAâ€”XXXXXXXX-X